/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => CSVViewerPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");

// csv-parser.ts
function parseCSV(csvText) {
  const rows = [];
  let currentRow = [];
  let currentCell = "";
  let inQuotes = false;
  let wasQuoted = false;
  for (let i = 0; i < csvText.length; i++) {
    const char = csvText[i];
    const nextChar = csvText[i + 1];
    if (inQuotes) {
      if (char === '"') {
        if (nextChar === '"') {
          currentCell += '"';
          i++;
        } else {
          inQuotes = false;
        }
      } else {
        currentCell += char;
      }
    } else {
      if (char === '"') {
        inQuotes = true;
        wasQuoted = true;
      } else if (char === ",") {
        currentRow.push(wasQuoted ? currentCell : currentCell.trim());
        currentCell = "";
        wasQuoted = false;
      } else if (char === "\n" || char === "\r" && nextChar === "\n") {
        currentRow.push(wasQuoted ? currentCell : currentCell.trim());
        if (currentRow.length > 0 && currentRow.some((cell) => cell !== "")) {
          rows.push(currentRow);
        }
        currentRow = [];
        currentCell = "";
        wasQuoted = false;
        if (char === "\r") i++;
      } else if (char !== "\r") {
        currentCell += char;
      }
    }
  }
  if (currentCell || currentRow.length > 0) {
    currentRow.push(wasQuoted ? currentCell : currentCell.trim());
    if (currentRow.some((cell) => cell !== "")) {
      rows.push(currentRow);
    }
  }
  return rows;
}
function serializeCSV(rows) {
  return rows.map(
    (row) => row.map((cell) => {
      if (cell.includes(",") || cell.includes('"') || cell.includes("\n")) {
        return '"' + cell.replace(/"/g, '""') + '"';
      }
      return cell;
    }).join(",")
  ).join("\n");
}
function parseTranscript(transcriptText, _format) {
  const blocks = transcriptText.replace(/\r\n?/g, "\n").split(/\n{2,}/).map((block) => block.split("\n").map((line) => line.trim()).filter((line) => line.length > 0));
  const cues = [];
  const timestampPattern = /((?:\d{2}:)?\d{2}:\d{2}[.,]\d{3})\s+-->\s+((?:\d{2}:)?\d{2}:\d{2}[.,]\d{3})/;
  for (const block of blocks) {
    if (block.length === 0) continue;
    const firstLine = block[0].toUpperCase();
    if (firstLine.startsWith("WEBVTT") || firstLine.startsWith("NOTE") || firstLine.startsWith("STYLE") || firstLine.startsWith("REGION")) {
      continue;
    }
    const timingLineIndex = block.findIndex((line) => line.includes("-->"));
    if (timingLineIndex === -1) continue;
    const timingMatch = block[timingLineIndex].match(timestampPattern);
    if (!timingMatch) continue;
    cues.push({
      number: cues.length + 1,
      start: timingMatch[1],
      end: timingMatch[2],
      text: block.slice(timingLineIndex + 1).join("\n")
    });
  }
  return cues;
}

// json-utils.ts
function validateJson(text) {
  try {
    const value = JSON.parse(text);
    return {
      valid: true,
      value,
      summary: getJsonSummary(value)
    };
  } catch (error) {
    return {
      valid: false,
      error: getJsonParseErrorMessage(text, error)
    };
  }
}
function formatJson(text, indent) {
  const parsed = validateJson(text);
  if (!parsed.valid) {
    return {
      success: false,
      error: parsed.error
    };
  }
  return {
    success: true,
    text: JSON.stringify(parsed.value, null, indent)
  };
}
function minifyJson(text) {
  const parsed = validateJson(text);
  if (!parsed.valid) {
    return {
      success: false,
      error: parsed.error
    };
  }
  return {
    success: true,
    text: JSON.stringify(parsed.value)
  };
}
function getJsonSummary(value) {
  if (Array.isArray(value)) {
    return `Array with ${value.length.toLocaleString()} ${value.length === 1 ? "item" : "items"}`;
  }
  if (value && typeof value === "object") {
    const keyCount = Object.keys(value).length;
    return `Object with ${keyCount.toLocaleString()} ${keyCount === 1 ? "key" : "keys"}`;
  }
  if (value === null) {
    return "JSON null";
  }
  return `JSON ${typeof value}`;
}
function getJsonParseErrorMessage(text, error) {
  const message = error instanceof Error ? error.message : "Invalid JSON";
  const position = getErrorPosition(message, text);
  if (position === null) {
    return message;
  }
  const { line, column } = getLineColumn(text, position);
  return `${message.replace(/\s*\(line \d+ column \d+\)$/, "")} at line ${line}, column ${column}`;
}
function getErrorPosition(message, text) {
  const positionMatch = message.match(/position\s+(\d+)/i);
  if (positionMatch) {
    return Number(positionMatch[1]);
  }
  if (/unexpected end/i.test(message)) {
    return text.length;
  }
  const tokenMatch = message.match(/unexpected token '(.+?)'/i);
  if (tokenMatch) {
    const tokenPosition = text.indexOf(tokenMatch[1] || "");
    return tokenPosition >= 0 ? tokenPosition : null;
  }
  return null;
}
function getLineColumn(text, position) {
  var _a;
  const beforeError = text.slice(0, position);
  const lines = beforeError.split(/\r\n|\r|\n/);
  return {
    line: lines.length,
    column: (((_a = lines[lines.length - 1]) == null ? void 0 : _a.length) || 0) + 1
  };
}

// support.ts
var SUPPORT_ISSUES_URL = "https://github.com/jethrojones/file-viewer/issues";

// main.ts
var CSV_VIEW_TYPE = "csv-view";
var LOG_VIEW_TYPE = "log-view";
var TRANSCRIPT_VIEW_TYPE = "transcript-view";
var JSON_VIEW_TYPE = "json-view";
var DEFAULT_SETTINGS = {
  enableCsvViewer: true,
  enableLogViewer: true,
  enableVttViewer: true,
  enableSrtViewer: true,
  enableJsonViewer: true
};
var CSVView = class extends import_obsidian.TextFileView {
  constructor() {
    super(...arguments);
    this.data = "";
    this.parsedRows = [];
    this.sortColumn = -1;
    this.sortAscending = true;
    this.editMode = false;
  }
  getViewType() {
    return CSV_VIEW_TYPE;
  }
  getDisplayText() {
    var _a;
    return ((_a = this.file) == null ? void 0 : _a.basename) || "CSV";
  }
  getIcon() {
    return "table";
  }
  onOpen() {
    this.contentEl.addClass("csv-view-container");
    return Promise.resolve();
  }
  onClose() {
    this.contentEl.empty();
    return Promise.resolve();
  }
  getViewData() {
    return this.data;
  }
  setViewData(data, _clear) {
    this.data = data;
    this.parsedRows = parseCSV(data);
    this.sortColumn = -1;
    this.sortAscending = true;
    this.renderCSV();
  }
  clear() {
    this.data = "";
    this.parsedRows = [];
    this.contentEl.empty();
  }
  getSortedRows() {
    if (this.parsedRows.length < 2) {
      return {
        rows: this.parsedRows,
        originalIndices: this.parsedRows.map((_, i) => i)
      };
    }
    const headers = this.parsedRows[0];
    const dataRows = this.parsedRows.slice(1);
    const originalIndices = dataRows.map((_, i) => i + 1);
    if (this.sortColumn < 0) {
      return {
        rows: [headers, ...dataRows],
        originalIndices: [0, ...originalIndices]
      };
    }
    const indexedRows = dataRows.map((row, i) => ({ row, originalIndex: i + 1 }));
    indexedRows.sort((a, b) => {
      const aVal = a.row[this.sortColumn] || "";
      const bVal = b.row[this.sortColumn] || "";
      const aNum = parseFloat(aVal.replace(/[,$%]/g, ""));
      const bNum = parseFloat(bVal.replace(/[,$%]/g, ""));
      if (!isNaN(aNum) && !isNaN(bNum)) {
        return this.sortAscending ? aNum - bNum : bNum - aNum;
      }
      const comparison = aVal.localeCompare(bVal, void 0, { numeric: true, sensitivity: "base" });
      return this.sortAscending ? comparison : -comparison;
    });
    return {
      rows: [headers, ...indexedRows.map((r) => r.row)],
      originalIndices: [0, ...indexedRows.map((r) => r.originalIndex)]
    };
  }
  renderCSV() {
    var _a;
    this.contentEl.empty();
    const container = this.contentEl.createDiv({ cls: "csv-view-content" });
    const { rows, originalIndices } = this.getSortedRows();
    if (rows.length === 0) {
      container.createEl("p", { text: "No data in CSV file", cls: "csv-view-info" });
      return;
    }
    const toolbar = container.createDiv({ cls: "csv-view-toolbar" });
    const searchInput = toolbar.createEl("input", {
      cls: "csv-view-search",
      attr: { type: "text", placeholder: "\u{1F50D} Search..." }
    });
    const editBtn = toolbar.createEl("button", {
      text: "Edit",
      cls: "csv-edit-btn" + (this.editMode ? " active" : "")
    });
    editBtn.addEventListener("click", () => {
      this.editMode = !this.editMode;
      this.renderCSV();
    });
    const info = toolbar.createDiv({ cls: "csv-view-info" });
    const dataRowCount = rows.length - 1;
    const colCount = ((_a = rows[0]) == null ? void 0 : _a.length) || 0;
    info.textContent = `${dataRowCount.toLocaleString()} rows \xB7 ${colCount} columns`;
    const tableWrapper = container.createDiv({ cls: "csv-table-wrapper" });
    const tableScroll = tableWrapper.createDiv({ cls: "csv-table-scroll" });
    const table = tableScroll.createEl("table", { cls: "csv-table" });
    const thead = table.createEl("thead");
    const headerRow = thead.createEl("tr");
    const headers = rows[0] || [];
    headers.forEach((header, index) => {
      const th = headerRow.createEl("th");
      const thContent = th.createDiv({ cls: "th-content" });
      thContent.createSpan({ text: header, cls: "th-text", attr: { title: header } });
      if (this.sortColumn === index) {
        th.addClass("sorted");
        thContent.createSpan({
          text: this.sortAscending ? "\u25B2" : "\u25BC",
          cls: "sort-indicator"
        });
      }
      if (this.editMode) {
        th.addClass("sort-disabled");
      } else {
        th.addEventListener("click", () => {
          if (this.sortColumn === index) {
            if (this.sortAscending) {
              this.sortAscending = false;
            } else {
              this.sortColumn = -1;
              this.sortAscending = true;
            }
          } else {
            this.sortColumn = index;
            this.sortAscending = true;
          }
          this.renderCSV();
        });
      }
    });
    const tbody = table.createEl("tbody");
    for (let i = 1; i < rows.length; i++) {
      const tr = tbody.createEl("tr");
      const originalRowIndex = originalIndices[i];
      for (let j = 0; j < headers.length; j++) {
        const cellValue = rows[i][j] || "";
        const td = tr.createEl("td", { text: cellValue, attr: { title: cellValue } });
        if (this.editMode) {
          td.setAttribute("contenteditable", "true");
          td.removeAttribute("title");
          td.addEventListener("paste", (e) => {
            var _a2;
            e.preventDefault();
            const text = ((_a2 = e.clipboardData) == null ? void 0 : _a2.getData("text/plain")) || "";
            const selection = window.getSelection();
            if (!selection || selection.rangeCount === 0) return;
            const range = selection.getRangeAt(0);
            range.deleteContents();
            range.insertNode(td.ownerDocument.createTextNode(text));
            range.collapse(false);
            selection.removeAllRanges();
            selection.addRange(range);
          });
          td.addEventListener("blur", () => {
            const newValue = td.textContent || "";
            if (newValue !== cellValue) {
              this.parsedRows[originalRowIndex][j] = newValue;
              this.data = serializeCSV(this.parsedRows);
              this.requestSave();
            }
          });
          td.addEventListener("keydown", (e) => {
            if (e.key === "Tab") {
              e.preventDefault();
              const allCells = Array.from(tbody.querySelectorAll("td[contenteditable]"));
              const currentIndex = allCells.indexOf(td);
              const nextIndex = e.shiftKey ? currentIndex - 1 : currentIndex + 1;
              if (nextIndex >= 0 && nextIndex < allCells.length) {
                allCells[nextIndex].focus();
              }
            } else if (e.key === "Escape") {
              td.blur();
            }
          });
        }
      }
    }
    searchInput.addEventListener("input", () => {
      const query = searchInput.value.toLowerCase();
      const bodyRows = tbody.querySelectorAll("tr");
      let visibleCount = 0;
      bodyRows.forEach((row) => {
        const cells = row.querySelectorAll("td");
        let matches = false;
        cells.forEach((cell) => {
          var _a2;
          const text = ((_a2 = cell.textContent) == null ? void 0 : _a2.toLowerCase()) || "";
          if (text.includes(query)) {
            matches = true;
            if (query) {
              cell.addClass("csv-highlight");
            } else {
              cell.removeClass("csv-highlight");
            }
          } else {
            cell.removeClass("csv-highlight");
          }
        });
        if (matches || !query) {
          row.removeClass("csv-row-hidden");
          visibleCount++;
        } else {
          row.addClass("csv-row-hidden");
        }
      });
      if (query) {
        info.textContent = `${visibleCount.toLocaleString()} of ${dataRowCount.toLocaleString()} rows`;
      } else {
        info.textContent = `${dataRowCount.toLocaleString()} rows \xB7 ${colCount} columns`;
      }
    });
  }
};
var LogView = class extends import_obsidian.TextFileView {
  constructor() {
    super(...arguments);
    this.data = "";
    this.lines = [];
    this.filteredLines = [];
    this.showErrors = true;
    this.showWarnings = true;
    this.showInfo = true;
    this.showDebug = true;
    this.autoScroll = true;
    this.searchQuery = "";
  }
  getViewType() {
    return LOG_VIEW_TYPE;
  }
  getDisplayText() {
    var _a;
    return ((_a = this.file) == null ? void 0 : _a.basename) || "Log";
  }
  getIcon() {
    return "file-text";
  }
  onOpen() {
    this.contentEl.addClass("log-view-container");
    return Promise.resolve();
  }
  onClose() {
    this.contentEl.empty();
    return Promise.resolve();
  }
  getViewData() {
    return this.data;
  }
  setViewData(data, _clear) {
    this.data = data;
    this.lines = data.split("\n").map((line, index) => ({
      number: index + 1,
      text: line,
      level: this.detectLogLevel(line)
    }));
    this.applyFilters();
    this.renderLog();
  }
  clear() {
    this.data = "";
    this.lines = [];
    this.filteredLines = [];
    this.contentEl.empty();
  }
  detectLogLevel(line) {
    const upper = line.toUpperCase();
    if (upper.includes("ERROR") || upper.includes("FATAL") || upper.includes("CRITICAL")) {
      return "error";
    }
    if (upper.includes("WARN")) {
      return "warning";
    }
    if (upper.includes("DEBUG") || upper.includes("TRACE")) {
      return "debug";
    }
    if (upper.includes("INFO")) {
      return "info";
    }
    return "default";
  }
  applyFilters() {
    const query = this.searchQuery.toLowerCase();
    this.filteredLines = this.lines.filter((line) => {
      if (line.level === "error" && !this.showErrors) return false;
      if (line.level === "warning" && !this.showWarnings) return false;
      if (line.level === "info" && !this.showInfo) return false;
      if (line.level === "debug" && !this.showDebug) return false;
      if (query) {
        return line.text.toLowerCase().includes(query);
      }
      return true;
    });
  }
  renderLog() {
    this.contentEl.empty();
    const container = this.contentEl.createDiv({ cls: "log-view-content" });
    const toolbar = container.createDiv({ cls: "log-view-toolbar" });
    const searchInput = toolbar.createEl("input", {
      cls: "log-view-search",
      attr: { type: "text", placeholder: "Filter..." }
    });
    searchInput.value = this.searchQuery;
    const errorBtn = this.createFilterButton(toolbar, "Errors", "error", this.showErrors);
    const warnBtn = this.createFilterButton(toolbar, "Warnings", "warning", this.showWarnings);
    const infoBtn = this.createFilterButton(toolbar, "Info", "info", this.showInfo);
    const debugBtn = this.createFilterButton(toolbar, "Debug", "debug", this.showDebug);
    const scrollBtn = toolbar.createEl("button", {
      text: "Auto-scroll",
      cls: "log-scroll-btn" + (this.autoScroll ? " active" : "")
    });
    const info = toolbar.createDiv({ cls: "log-view-info" });
    const logLines = container.createDiv({ cls: "log-lines" });
    searchInput.addEventListener("input", () => {
      this.searchQuery = searchInput.value;
      this.applyFilters();
      this.renderLogLines(logLines, info);
    });
    errorBtn.addEventListener("click", () => {
      this.showErrors = !this.showErrors;
      errorBtn.toggleClass("active", this.showErrors);
      this.applyFilters();
      this.renderLogLines(logLines, info);
    });
    warnBtn.addEventListener("click", () => {
      this.showWarnings = !this.showWarnings;
      warnBtn.toggleClass("active", this.showWarnings);
      this.applyFilters();
      this.renderLogLines(logLines, info);
    });
    infoBtn.addEventListener("click", () => {
      this.showInfo = !this.showInfo;
      infoBtn.toggleClass("active", this.showInfo);
      this.applyFilters();
      this.renderLogLines(logLines, info);
    });
    debugBtn.addEventListener("click", () => {
      this.showDebug = !this.showDebug;
      debugBtn.toggleClass("active", this.showDebug);
      this.applyFilters();
      this.renderLogLines(logLines, info);
    });
    scrollBtn.addEventListener("click", () => {
      this.autoScroll = !this.autoScroll;
      scrollBtn.toggleClass("active", this.autoScroll);
      if (this.autoScroll) {
        logLines.scrollTop = logLines.scrollHeight;
      }
    });
    this.renderLogLines(logLines, info);
  }
  createFilterButton(parent, text, level, active) {
    return parent.createEl("button", {
      text,
      cls: `log-filter-btn ${level}` + (active ? " active" : "")
    });
  }
  renderLogLines(container, info) {
    container.empty();
    if (this.filteredLines.length === 0) {
      container.createDiv({ cls: "log-empty", text: "No matching log lines" });
      info.textContent = `0 of ${this.lines.length.toLocaleString()} lines`;
      return;
    }
    info.textContent = `${this.filteredLines.length.toLocaleString()} of ${this.lines.length.toLocaleString()} lines`;
    for (const line of this.filteredLines) {
      const lineEl = container.createDiv({ cls: `log-line ${line.level}` });
      lineEl.createDiv({ cls: "log-line-number", text: String(line.number) });
      const textEl = lineEl.createDiv({ cls: "log-line-text" });
      this.renderLogLineText(textEl, line.text || " ");
    }
    if (this.autoScroll) {
      container.scrollTop = container.scrollHeight;
    }
  }
  renderLogLineText(parent, text) {
    const timestampPattern = /\d{4}-\d{2}-\d{2}[T\s]\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:Z|[+-]\d{2}:?\d{2})?|\[\d{4}-\d{2}-\d{2}\s\d{2}:\d{2}:\d{2}\]/g;
    const matches = this.findTextMatches(text, this.searchQuery, timestampPattern);
    for (const match of matches) {
      if (match.className) {
        parent.createSpan({ text: match.text, cls: match.className });
      } else {
        parent.appendText(match.text);
      }
    }
  }
  findTextMatches(text, query, timestampPattern) {
    const ranges = [];
    let timestampMatch;
    while ((timestampMatch = timestampPattern.exec(text)) !== null) {
      ranges.push({
        start: timestampMatch.index,
        end: timestampMatch.index + timestampMatch[0].length,
        className: "log-timestamp"
      });
    }
    if (query) {
      const lowerText = text.toLowerCase();
      const lowerQuery = query.toLowerCase();
      let index = lowerText.indexOf(lowerQuery);
      while (index !== -1) {
        ranges.push({
          start: index,
          end: index + query.length,
          className: "log-highlight"
        });
        index = lowerText.indexOf(lowerQuery, index + query.length);
      }
    }
    ranges.sort((a, b) => a.start - b.start || b.end - a.end);
    const segments = [];
    let position = 0;
    for (const range of ranges) {
      if (range.start < position) continue;
      if (range.start > position) {
        segments.push({ text: text.slice(position, range.start) });
      }
      segments.push({
        text: text.slice(range.start, range.end),
        className: range.className
      });
      position = range.end;
    }
    if (position < text.length) {
      segments.push({ text: text.slice(position) });
    }
    return segments.length > 0 ? segments : [{ text }];
  }
};
var TranscriptView = class extends import_obsidian.TextFileView {
  constructor() {
    super(...arguments);
    this.data = "";
    this.cues = [];
    this.filteredCues = [];
    this.searchQuery = "";
  }
  getViewType() {
    return TRANSCRIPT_VIEW_TYPE;
  }
  getDisplayText() {
    var _a;
    return ((_a = this.file) == null ? void 0 : _a.basename) || "Transcript";
  }
  getIcon() {
    return "captions";
  }
  onOpen() {
    this.contentEl.addClass("transcript-view-container");
    return Promise.resolve();
  }
  onClose() {
    this.contentEl.empty();
    return Promise.resolve();
  }
  getViewData() {
    return this.data;
  }
  setViewData(data, _clear) {
    this.data = data;
    this.cues = parseTranscript(data, this.getTranscriptFormat());
    this.applyFilters();
    this.renderTranscript();
  }
  clear() {
    this.data = "";
    this.cues = [];
    this.filteredCues = [];
    this.contentEl.empty();
  }
  getTranscriptFormat() {
    var _a, _b;
    return ((_b = (_a = this.file) == null ? void 0 : _a.extension) == null ? void 0 : _b.toLowerCase()) === "srt" ? "srt" : "vtt";
  }
  applyFilters() {
    const query = this.searchQuery.toLowerCase();
    this.filteredCues = this.cues.filter((cue) => {
      if (!query) return true;
      return cue.text.toLowerCase().includes(query) || cue.start.toLowerCase().includes(query) || cue.end.toLowerCase().includes(query);
    });
  }
  renderTranscript() {
    this.contentEl.empty();
    const container = this.contentEl.createDiv({ cls: "transcript-view-content" });
    const toolbar = container.createDiv({ cls: "transcript-view-toolbar" });
    const searchInput = toolbar.createEl("input", {
      cls: "transcript-view-search",
      attr: { type: "text", placeholder: "Filter transcript..." }
    });
    searchInput.value = this.searchQuery;
    const info = toolbar.createDiv({ cls: "transcript-view-info" });
    const cueList = container.createDiv({ cls: "transcript-cues" });
    searchInput.addEventListener("input", () => {
      this.searchQuery = searchInput.value;
      this.applyFilters();
      this.renderTranscriptCues(cueList, info);
    });
    this.renderTranscriptCues(cueList, info);
  }
  renderTranscriptCues(container, info) {
    container.empty();
    if (this.filteredCues.length === 0) {
      container.createDiv({ cls: "transcript-empty", text: "No matching transcript cues" });
      info.textContent = `0 of ${this.cues.length.toLocaleString()} cues`;
      return;
    }
    info.textContent = `${this.filteredCues.length.toLocaleString()} of ${this.cues.length.toLocaleString()} cues`;
    for (const cue of this.filteredCues) {
      const cueEl = container.createDiv({ cls: "transcript-cue" });
      const metaEl = cueEl.createDiv({ cls: "transcript-cue-meta" });
      metaEl.createSpan({ cls: "transcript-cue-number", text: String(cue.number) });
      metaEl.createSpan({ cls: "transcript-cue-time", text: `${cue.start} -> ${cue.end}` });
      const textEl = cueEl.createDiv({ cls: "transcript-cue-text" });
      this.renderTranscriptText(textEl, cue.text || " ");
    }
  }
  renderTranscriptText(parent, text) {
    const lines = text.split("\n");
    lines.forEach((line, index) => {
      if (index > 0) {
        parent.createEl("br");
      }
      for (const segment of this.findTextMatches(line, this.searchQuery)) {
        if (segment.className) {
          parent.createSpan({ text: segment.text, cls: segment.className });
        } else {
          parent.appendText(segment.text);
        }
      }
    });
  }
  findTextMatches(text, query) {
    if (!query) return [{ text }];
    const segments = [];
    const lowerText = text.toLowerCase();
    const lowerQuery = query.toLowerCase();
    let position = 0;
    let index = lowerText.indexOf(lowerQuery);
    while (index !== -1) {
      if (index > position) {
        segments.push({ text: text.slice(position, index) });
      }
      segments.push({
        text: text.slice(index, index + query.length),
        className: "transcript-highlight"
      });
      position = index + query.length;
      index = lowerText.indexOf(lowerQuery, position);
    }
    if (position < text.length) {
      segments.push({ text: text.slice(position) });
    }
    return segments.length > 0 ? segments : [{ text }];
  }
};
var JsonView = class extends import_obsidian.TextFileView {
  constructor() {
    super(...arguments);
    this.data = "";
    this.indentSize = 2;
  }
  getViewType() {
    return JSON_VIEW_TYPE;
  }
  getDisplayText() {
    var _a;
    return ((_a = this.file) == null ? void 0 : _a.basename) || "JSON";
  }
  getIcon() {
    return "braces";
  }
  onOpen() {
    this.contentEl.addClass("json-view-container");
    return Promise.resolve();
  }
  onClose() {
    this.contentEl.empty();
    return Promise.resolve();
  }
  getViewData() {
    var _a, _b;
    return (_b = (_a = this.editorEl) == null ? void 0 : _a.value) != null ? _b : this.data;
  }
  setViewData(data, _clear) {
    this.data = data;
    this.renderJson();
  }
  clear() {
    this.data = "";
    this.contentEl.empty();
  }
  renderJson() {
    this.contentEl.empty();
    const container = this.contentEl.createDiv({ cls: "json-view-content" });
    const toolbar = container.createDiv({ cls: "json-view-toolbar" });
    const validateBtn = toolbar.createEl("button", {
      text: "Validate",
      cls: "json-action-btn"
    });
    const formatBtn = toolbar.createEl("button", {
      text: "Format",
      cls: "json-action-btn"
    });
    const minifyBtn = toolbar.createEl("button", {
      text: "Minify",
      cls: "json-action-btn"
    });
    const indentSelect = toolbar.createEl("select", {
      cls: "json-indent-select",
      attr: { "aria-label": "JSON indentation size" }
    });
    indentSelect.createEl("option", { text: "2 Spaces", value: "2" });
    indentSelect.createEl("option", { text: "4 Spaces", value: "4" });
    indentSelect.value = String(this.indentSize);
    const status = toolbar.createDiv({ cls: "json-view-info" });
    const editor = container.createEl("textarea", {
      cls: "json-editor",
      attr: {
        "aria-label": "JSON editor",
        autocapitalize: "off",
        autocomplete: "off",
        autocorrect: "off",
        spellcheck: "false",
        wrap: "off"
      }
    });
    editor.value = this.data;
    this.editorEl = editor;
    this.statusEl = status;
    indentSelect.addEventListener("change", () => {
      this.indentSize = Number(indentSelect.value);
    });
    validateBtn.addEventListener("click", () => {
      const isValid = this.updateValidationStatus();
      new import_obsidian.Notice(isValid ? "JSON is valid." : "JSON needs a fix before formatting.");
    });
    formatBtn.addEventListener("click", () => {
      this.applyJsonTransform(formatJson(this.getViewData(), this.indentSize), "JSON formatted.");
    });
    minifyBtn.addEventListener("click", () => {
      this.applyJsonTransform(minifyJson(this.getViewData()), "JSON minified.");
    });
    editor.addEventListener("input", () => {
      this.data = editor.value;
      this.updateValidationStatus();
      this.requestSave();
    });
    this.updateValidationStatus();
  }
  applyJsonTransform(result, successNotice) {
    if (!result.success) {
      this.updateValidationStatus(result.error);
      new import_obsidian.Notice("JSON needs a fix before formatting.");
      return;
    }
    this.data = result.text;
    if (this.editorEl) {
      this.editorEl.value = result.text;
      this.editorEl.focus();
    }
    this.updateValidationStatus();
    this.requestSave();
    new import_obsidian.Notice(successNotice);
  }
  updateValidationStatus(errorOverride) {
    if (!this.statusEl) return false;
    if (errorOverride) {
      this.statusEl.setText(errorOverride);
      this.statusEl.removeClass("valid");
      this.statusEl.addClass("error");
      return false;
    }
    const result = validateJson(this.getViewData());
    if (result.valid) {
      this.statusEl.setText(result.summary);
      this.statusEl.removeClass("error");
      this.statusEl.addClass("valid");
      return true;
    }
    this.statusEl.setText(result.error);
    this.statusEl.removeClass("valid");
    this.statusEl.addClass("error");
    return false;
  }
};
var CSVViewerPlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    this.registerView(CSV_VIEW_TYPE, (leaf) => new CSVView(leaf));
    this.registerView(LOG_VIEW_TYPE, (leaf) => new LogView(leaf));
    this.registerView(TRANSCRIPT_VIEW_TYPE, (leaf) => new TranscriptView(leaf));
    this.registerView(JSON_VIEW_TYPE, (leaf) => new JsonView(leaf));
    if (this.settings.enableCsvViewer) {
      this.registerExtensions(["csv"], CSV_VIEW_TYPE);
    }
    if (this.settings.enableLogViewer) {
      this.registerExtensions(["log"], LOG_VIEW_TYPE);
    }
    if (this.settings.enableVttViewer) {
      this.registerExtensions(["vtt"], TRANSCRIPT_VIEW_TYPE);
    }
    if (this.settings.enableSrtViewer) {
      this.registerExtensions(["srt"], TRANSCRIPT_VIEW_TYPE);
    }
    if (this.settings.enableJsonViewer) {
      this.registerExtensions(["json"], JSON_VIEW_TYPE);
    }
    this.addSettingTab(new CSVViewerSettingTab(this.app, this));
  }
  async loadSettings() {
    const savedSettings = await this.loadData();
    this.settings = {
      ...DEFAULT_SETTINGS,
      ...this.parseSettings(savedSettings)
    };
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  parseSettings(settings) {
    if (!settings || typeof settings !== "object") {
      return {};
    }
    const candidate = settings;
    return {
      ...typeof candidate.enableCsvViewer === "boolean" ? { enableCsvViewer: candidate.enableCsvViewer } : {},
      ...typeof candidate.enableLogViewer === "boolean" ? { enableLogViewer: candidate.enableLogViewer } : {},
      ...typeof candidate.enableVttViewer === "boolean" ? { enableVttViewer: candidate.enableVttViewer } : {},
      ...typeof candidate.enableSrtViewer === "boolean" ? { enableSrtViewer: candidate.enableSrtViewer } : {},
      ...typeof candidate.enableJsonViewer === "boolean" ? { enableJsonViewer: candidate.enableJsonViewer } : {}
    };
  }
};
var CSVViewerSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("CSV viewer").setDesc("Open .csv files in the interactive table viewer.").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableCsvViewer).onChange(async (value) => {
      this.plugin.settings.enableCsvViewer = value;
      await this.plugin.saveSettings();
      new import_obsidian.Notice("Reload this plugin for file type changes to take effect.");
    }));
    new import_obsidian.Setting(containerEl).setName("Log viewer").setDesc("Open .log files in the filtered log viewer.").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableLogViewer).onChange(async (value) => {
      this.plugin.settings.enableLogViewer = value;
      await this.plugin.saveSettings();
      new import_obsidian.Notice("Reload this plugin for file type changes to take effect.");
    }));
    new import_obsidian.Setting(containerEl).setName(".vtt transcript viewer").setDesc("Open .vtt files in the transcript viewer.").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableVttViewer).onChange(async (value) => {
      this.plugin.settings.enableVttViewer = value;
      await this.plugin.saveSettings();
      new import_obsidian.Notice("Reload this plugin for file type changes to take effect.");
    }));
    new import_obsidian.Setting(containerEl).setName(".srt transcript viewer").setDesc("Open .srt files in the transcript viewer.").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableSrtViewer).onChange(async (value) => {
      this.plugin.settings.enableSrtViewer = value;
      await this.plugin.saveSettings();
      new import_obsidian.Notice("Reload this plugin for file type changes to take effect.");
    }));
    new import_obsidian.Setting(containerEl).setName("JSON viewer").setDesc("Open .json files in an editable JSON viewer with validation and formatting controls.").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableJsonViewer).onChange(async (value) => {
      this.plugin.settings.enableJsonViewer = value;
      await this.plugin.saveSettings();
      new import_obsidian.Notice("Reload this plugin for file type changes to take effect.");
    }));
    new import_obsidian.Setting(containerEl).setName("Feedback").setDesc("Report a bug or suggest a feature on GitHub.").addButton((button) => button.setButtonText("Open issues").onClick(() => {
      window.open(SUPPORT_ISSUES_URL);
    }));
  }
};

/* nosourcemap */